name: "Terraform Lint & Validate"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-checks:
    name: "Check AWS and GCP Code"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check AWS Syntax
        run: |
          cd aws
          terraform init -backend=false
          terraform validate

      - name: Check GCP Syntax
        run: |
          cd gcp
          terraform init -backend=false
          terraform validate